name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            .pio/cache
          key: ${{ runner.os }}-pio-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install --upgrade platformio
      - run: pio run
      - uses: actions/cache/save@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            .pio/cache
          key: ${{ runner.os }}-pio-${{ github.run_id }}
